// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzUmojQgKpqXwg3qlbnImFMcc_JGSu9Rw',
    appId: '1:483774057933:web:e6e1582b552734a8f24884',
    messagingSenderId: '483774057933',
    projectId: 'fir-secondproject-aa0d5',
    authDomain: 'fir-secondproject-aa0d5.firebaseapp.com',
    storageBucket: 'fir-secondproject-aa0d5.appspot.com',
    measurementId: 'G-337RKTLSZ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdqC_cuFGsjEXFEiC0AenJ5VzTESju4pU',
    appId: '1:483774057933:android:e02c77f8773cb22bf24884',
    messagingSenderId: '483774057933',
    projectId: 'fir-secondproject-aa0d5',
    storageBucket: 'fir-secondproject-aa0d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsbPN_XwbWXJnYAp1x8aUSKMM4kv1lZ3o',
    appId: '1:483774057933:ios:5a7aead356e2017ff24884',
    messagingSenderId: '483774057933',
    projectId: 'fir-secondproject-aa0d5',
    storageBucket: 'fir-secondproject-aa0d5.appspot.com',
    iosBundleId: 'com.example.authenticationFirebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsbPN_XwbWXJnYAp1x8aUSKMM4kv1lZ3o',
    appId: '1:483774057933:ios:8dada1604ec9979ff24884',
    messagingSenderId: '483774057933',
    projectId: 'fir-secondproject-aa0d5',
    storageBucket: 'fir-secondproject-aa0d5.appspot.com',
    iosBundleId: 'com.example.authenticationFirebaseApp.RunnerTests',
  );
}
